trigger: none

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo apt-get update
    sudo apt-get install -y wget unzip

    wget -q https://releases.hashicorp.com/terraform/1.13.3/terraform_1.13.3_linux_amd64.zip

    unzip -o terraform_1.13.3_linux_amd64.zip

    sudo mv terraform /usr/local/bin/

    terraform --version
  displayName: 'Install Terraform'


- task: AzureCLI@2
  displayName: 'Terraform Init Validate Plan'
  inputs:
    azureSubscription: 'cicd_pipeline'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      echo "Azure account:"
      az account show

      echo "Terraform version:"
      terraform --version

      echo "Terraform Init:"
      terraform init

      echo "Removing stale Terraform state lock:"
      terraform force-unlock -force d884f118-0fd1-175f-f172-f0fb00c08f3e

      echo "Terraform Validate:"
      terraform validate

      echo "Terraform Plan:"
      terraform plan -var="subscription_id=$(az account show --query id -o tsv)"
